import { portfolioFixture } from '../portfolio-fixture.mjs';
export function registerScenarioTests({test,expect,setup,composer,owner,created}) {
  test('network: overview cooperative PAs, summary, descending sorts and responsive layout',async({page},testInfo)=>{
    const {errors}=await setup(page);
    await page.getByLabel('Central',{exact:true}).selectOption('1002');
    await page.getByLabel('Período',{exact:true}).selectOption('month');
    await page.getByLabel('Mês de referência',{exact:true}).selectOption('7');
    await expect(page.getByRole('region',{name:'Resumo da rede filtrada'})).toContainText('2');
    await page.getByLabel('Ordenar análise').selectOption('attainment-desc');
    const table=page.locator('.table-panel tbody');
    await expect(table.locator('tr').first()).toContainText('Cooperativa Beta');
    await page.getByLabel('Ordenar análise').selectOption('production');
    await expect(table.locator('tr').first()).toContainText('Cooperativa Beta');
    await page.getByRole('button',{name:'Ver PAs de Cooperativa Alfa',exact:true}).click();
    const pas=page.getByRole('region',{name:'PAs da cooperativa',exact:true});
    await expect(pas.locator('tbody tr')).toHaveCount(1);
    await expect(pas).toContainText('PA Alfa zero');await expect(pas).not.toContainText('PA Beta zero');
    await expect(pas.getByRole('columnheader',{name:'GAP',exact:true})).toBeVisible();
    await page.screenshot({path:testInfo.outputPath('scenario-desktop.png'),fullPage:true});
    await page.setViewportSize({width:390,height:844});
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBe(true);
    await page.screenshot({path:testInfo.outputPath('scenario-mobile.png'),fullPage:true});
    expect(errors).toEqual([]);
  });
  test('historical: compare stored years with same closed months and full hierarchy',async({page})=>{
    const {errors}=await setup(page);
    const dataset=portfolioFixture();
    const previous=JSON.parse(JSON.stringify(dataset).replaceAll('2026','2025'));
    previous.registry.entities=previous.registry.entities.filter(entry=>entry.cooperative!=='3025');
    previous.rows=previous.rows.filter(row=>row.cooperative!=='3025');
    previous.rows.forEach(row=>{row.actuals=row.actuals.map(value=>value==null?null:value/2);});
    const rows=[dataset,previous].map((value,index)=>({id:`00000000-0000-0000-0000-00000000001${index}`,owner_id:owner,year:value.year,revision:1,updated_at:created,dataset:value}));
    await page.route('https://portfolio-test.supabase.co/rest/v1/commercial_workspaces**',async route=>{
      const url=new URL(route.request().url()),year=url.searchParams.get('year');
      const filtered=year?rows.filter(row=>`eq.${row.year}`===year):rows;
      await route.fulfill({status:200,contentType:'application/json',headers:{'access-control-allow-origin':'*'},body:JSON.stringify((route.request().headers().accept||'').includes('vnd.pgrst.object')?filtered[0]||null:filtered)});
    });
    await page.getByRole('button',{name:'Recarregar cadastro salvo',exact:true}).click();
    await page.getByLabel('Central',{exact:true}).selectOption('1002');
    await page.getByLabel('Período',{exact:true}).selectOption('ytd');
    await page.getByLabel('Mês de referência',{exact:true}).selectOption('7');
    await page.getByRole('button',{name:'Comparar anos',exact:true}).click();
    const comparison=page.getByRole('region',{name:'Comparativo entre anos',exact:true});
    await expect(comparison.getByLabel('Comparar 2026 com')).toHaveValue('2025');
    await expect(comparison).toContainText('JAN a AGO');
    await expect(comparison.locator('tbody tr')).toHaveCount(2);
    await expect(comparison).toContainText('Somente no cadastro de 2026');
    await comparison.getByLabel('Somente unidades presentes nos dois anos').check();
    await expect(comparison.locator('tbody tr')).toHaveCount(1);
    await expect(comparison.locator('tbody')).toContainText('100,0%');
    expect(errors).toEqual([]);
  });
  test('texts: editable channels, optional private default, restore and disable persistence',async({page})=>{
    const {errors,writes}=await setup(page);
    await page.getByRole('button',{name:'Gerar e-mail / WhatsApp',exact:true}).click();
    let dialog=composer(page);
    await dialog.getByLabel('Unidade selecionada').selectOption('cooperative:1002:3017');
    await dialog.getByLabel('Texto / modelo do e-mail',{exact:true}).fill('Olá {{unidade}}!\n{{cenario}}\nVamos atuar.');
    await dialog.getByLabel('Texto / modelo do WhatsApp',{exact:true}).fill('Equipe: {{unidade}} / {{ano}}\n{{cenario}}');
    await dialog.getByLabel('Usar como padrão para este nível e carteira').check();
    await dialog.getByRole('button',{name:'Salvar preferência de texto'}).click();
    await expect(dialog.getByRole('status')).toContainText('Modelo padrão salvo');
    const outlook=new URL(await dialog.getByRole('link',{name:'Abrir Outlook',exact:true}).getAttribute('href'));
    expect(outlook.searchParams.get('body')).toContain('Olá Cooperativa Alfa!');
    await dialog.getByRole('button',{name:'Fechar comunicação'}).click();
    await page.getByRole('button',{name:'Gerar e-mail / WhatsApp',exact:true}).click();
    dialog=composer(page);await dialog.getByLabel('Unidade selecionada').selectOption('cooperative:1002:3017');
    await expect(dialog.getByLabel('Texto / modelo do e-mail',{exact:true})).toHaveValue(/Vamos atuar/);
    await dialog.getByRole('button',{name:'Editar texto completo do WhatsApp',exact:true}).click();
    await expect(dialog.getByLabel('Texto / modelo do WhatsApp',{exact:true})).toHaveValue(/Cooperativa Alfa/);
    await dialog.getByLabel('Texto / modelo do WhatsApp',{exact:true}).fill('Texto revisado manualmente.');
    expect(new URL(await dialog.getByRole('link',{name:'Abrir WhatsApp',exact:true}).getAttribute('href')).searchParams.get('text')).toBe('Texto revisado manualmente.');
    await dialog.getByRole('button',{name:'Salvar rascunho',exact:true}).click();
    await expect.poll(()=>writes.length).toBe(1);expect(writes[0].whatsapp_body).toBe('Texto revisado manualmente.');
    await dialog.getByLabel('Usar como padrão para este nível e carteira').uncheck();
    await dialog.getByRole('button',{name:'Salvar preferência de texto'}).click();
    await expect(dialog.getByText('Padrão desativado.',{exact:false})).toBeVisible();
    await dialog.getByRole('button',{name:'Fechar comunicação'}).click();
    await page.getByRole('button',{name:'Gerar e-mail / WhatsApp',exact:true}).click();
    dialog=composer(page);await dialog.getByLabel('Unidade selecionada').selectOption('cooperative:1002:3017');
    await expect(dialog.getByLabel('Texto / modelo do WhatsApp',{exact:true})).toHaveValue('{{cenario}}');
    await dialog.getByLabel('Texto / modelo do e-mail',{exact:true}).fill('{{cenario}}{{cenario}}');
    await expect(dialog.getByRole('button',{name:'Abrir Outlook',exact:true})).toBeDisabled();
    expect(errors).toEqual([]);
  });
}
