import { portfolioFixture } from '../portfolio-fixture.mjs';
export function registerUxTests({test,expect,setup,owner,created}) {
 test('UX: primary data comes before optional panels; PAs toggle by keyboard and selected unit',async({page},testInfo)=>{
  const {errors}=await setup(page);
  await page.getByRole('combobox',{name:'Período',exact:true}).selectOption('month');
  await page.getByRole('combobox',{name:'Mês de referência',exact:true}).selectOption('7');
  await page.getByRole('button',{name:'Fechar mensagem',exact:true}).click();
  await expect(page.getByRole('heading',{level:1,name:'Visão geral',exact:true})).toBeVisible();
  const result=page.getByRole('region',{name:'Resultado do período',exact:true}),list=page.getByRole('region',{name:'Lista de unidades',exact:true});
  expect((await result.boundingBox()).y).toBeLessThan((await list.boundingBox()).y);
  expect((await list.boundingBox()).y).toBeLessThan((await page.getByRole('region',{name:'Comparativo entre anos',exact:true}).boundingBox()).y);
  await expect(list.getByRole('columnheader',{name:'GAP',exact:true})).toBeVisible();
  await expect(list.getByRole('columnheader',{name:'Projeção',exact:true})).toHaveCount(0);
  await list.getByLabel('Mais indicadores').check();await expect(list.getByRole('columnheader',{name:'Projeção',exact:true})).toBeVisible();
  await list.getByLabel('Mais indicadores').uncheck();
  await page.screenshot({path:testInfo.outputPath('ux-overview-desktop.png'),fullPage:true});
  await page.getByRole('combobox',{name:'Cooperativa',exact:true}).selectOption('1002:3017');
  const pas=page.getByRole('region',{name:'PAs da cooperativa',exact:true});
  await expect(pas.getByRole('button',{name:'Abrir PAs',exact:true})).toHaveAttribute('aria-expanded','false');
  await expect(pas.locator('table')).toBeHidden();
  await pas.getByRole('button',{name:'Abrir PAs',exact:true}).focus();await page.keyboard.press('Enter');await expect(pas.locator('table')).toBeVisible();
  await pas.getByRole('button',{name:'Fechar PAs',exact:true}).focus();await page.keyboard.press('Space');await expect(pas.locator('table')).toBeHidden();
  await page.getByRole('button',{name:'Ver PAs de Cooperativa Alfa',exact:true}).click();await expect(pas.locator('table')).toBeVisible();
  await page.getByRole('combobox',{name:'Cooperativa',exact:true}).selectOption('1002:3025');await expect(pas.locator('table')).toBeHidden();
  await pas.getByRole('button',{name:'Abrir PAs',exact:true}).click();await expect(pas).toContainText('PA Beta zero');await expect(pas).not.toContainText('PA Alfa zero');
  await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
  await page.screenshot({path:testInfo.outputPath('ux-overview-mobile.png'),fullPage:true});
  expect(errors).toEqual([]);
 });
 test('UX: actions and audit exclude unrelated comparisons; hidden simulation stays explicit',async({page},testInfo)=>{
  const {errors}=await setup(page);
  await page.locator('summary').filter({hasText:'Evolução e simulação'}).click();
  await page.getByLabel('Simular aumento de ritmo').focus();
  await page.keyboard.press('Home');
  for(let step=0;step<5;step++)await page.keyboard.press('ArrowRight');
  await expect(page.getByLabel('Simular aumento de ritmo')).toHaveValue('25');
  await page.locator('summary').filter({hasText:'Evolução e simulação'}).click();
  await expect(page.getByText('Simulação de ritmo +25% ativa · somente projeções',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Limpar simulação',exact:true}).click();
  await page.getByRole('button',{name:'Plano de ação',exact:true}).click();
  await expect(page.getByRole('region',{name:'Lista de ações',exact:true})).toBeVisible();
  await expect(page.getByRole('region',{name:'Comparativo entre anos',exact:true})).toHaveCount(0);
  await expect(page.getByRole('region',{name:'Resumo da rede filtrada',exact:true})).toHaveCount(0);
  await page.getByRole('combobox',{name:'Ordenar análise',exact:true}).selectOption('production');
  await page.getByLabel('Buscar cooperativa ou PA').fill('Alfa');await expect(page.locator('.action-card')).toHaveCount(1);
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:testInfo.outputPath('ux-actions-mobile.png'),fullPage:true});
  await page.getByRole('button',{name:'Conferência da base',exact:true}).click();
  await expect(page.getByRole('region',{name:'Comparativo entre anos',exact:true})).toHaveCount(0);
  await expect(page.getByRole('heading',{name:'Conferência das fontes',exact:true})).toBeVisible();
  await expect(page.getByText('REGRAS DE CÁLCULO',{exact:true})).toBeHidden();
  expect(errors).toEqual([]);
 });
 test('UX: visual comparison reflects current filters, lazy loading and mobile dashboard',async({page},testInfo)=>{
  const {errors}=await setup(page),current=portfolioFixture();
  const previous=JSON.parse(JSON.stringify(current).replaceAll('2026','2025'));
  previous.rows.forEach(row=>{row.actuals=row.actuals.map(value=>value==null?null:value/2);});
  const datasets=[current,previous];let historicalReads=0;
  await page.route('https://portfolio-test.supabase.co/rest/v1/commercial_workspaces**',async route=>{
    if(route.request().method()==='OPTIONS')return route.fulfill({status:204,headers:{'access-control-allow-origin':'*','access-control-allow-headers':'*','access-control-allow-methods':'*'}});
    const url=new URL(route.request().url()),year=url.searchParams.get('year');if(year==='eq.2025')historicalReads++;
    const rows=datasets.filter(value=>!year||`eq.${value.year}`===year).map((dataset,index)=>({id:`00000000-0000-0000-0000-00000000001${index}`,owner_id:owner,year:dataset.year,revision:1,updated_at:created,dataset}));
    await route.fulfill({status:200,contentType:'application/json',headers:{'access-control-allow-origin':'*'},body:JSON.stringify((route.request().headers().accept||'').includes('vnd.pgrst.object')?rows[0]||null:rows)});
  });
  await page.getByRole('button',{name:'Recarregar cadastro salvo',exact:true}).click();
  await page.getByRole('combobox',{name:'Central',exact:true}).selectOption('1002');
  await expect(page.getByLabel('Abrangência do período',{exact:true})).toContainText('JAN–SET/2026');
  expect(historicalReads).toBe(0);
  const comparison=page.getByRole('region',{name:'Comparativo entre anos',exact:true});
  await comparison.getByRole('button',{name:'Comparar anos',exact:true}).click();
  await expect(comparison.getByLabel('Dashboard comparativo',{exact:true})).toBeVisible();
  await expect(comparison.getByLabel('Resumo de 2026',{exact:true})).toContainText('1.600,00');
  await expect(comparison.getByLabel('Resumo de 2025',{exact:true})).toContainText('800,00');
  await expect(comparison.getByLabel('Variação da produção',{exact:true})).toContainText('800,00');
  await expect(comparison.getByLabel('Comparação do atingimento',{exact:true})).toContainText('+50 p.p.');
  await expect(comparison.locator('.comparison-unit-table')).toBeHidden();
  await comparison.screenshot({path:testInfo.outputPath('ux-comparison-desktop.png')});
  await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
  await comparison.screenshot({path:testInfo.outputPath('ux-comparison-mobile.png')});
  await page.getByRole('combobox',{name:'Cooperativa',exact:true}).selectOption('1002:3017');
  await expect(comparison.getByLabel('Resumo de 2026',{exact:true})).toContainText('400,00');
  await page.getByRole('combobox',{name:'Período',exact:true}).selectOption('month');
  await page.getByRole('combobox',{name:'Mês de referência',exact:true}).selectOption('8');
  await expect(comparison.getByLabel('Dashboard comparativo',{exact:true})).toHaveCount(0);
  await expect(comparison).toContainText('Não há mês fechado comum');
  expect(errors).toEqual([]);
 });
}
