import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile, readdir } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';
import { installAuthFixture } from './auth-db-fixture.mjs';
const A='00000000-0000-0000-0000-000000000001', B='00000000-0000-0000-0000-000000000002';
const TABLES=['commercial_imports','commercial_actions','commercial_workspaces','commercial_entity_contacts','commercial_communication_drafts','commercial_message_templates'];
test('security: real PostgreSQL RLS requires approval, verified email and active matching session on every business table', async () => {
  const db=new PGlite();
  try {
    await db.exec(`create schema auth; create role anon; create role authenticated;
      create table auth.users(id uuid primary key);
      create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
      grant usage on schema auth to authenticated,anon; grant execute on function auth.uid() to authenticated,anon;
      insert into auth.users values ('${A}'),('${B}');`);
    await installAuthFixture(db);
    const dir=new URL('../supabase/migrations/',import.meta.url);
    for(const file of (await readdir(dir)).filter(f=>f.endsWith('.sql')).sort()) await db.exec(await readFile(new URL(file,dir),'utf8'));
    const asUser=async(id=A,claims={})=>{ await db.exec('reset role; set role authenticated;'); await db.query("select set_config('request.jwt.claim.sub',$1,false),set_config('request.jwt.claims',$2,false)",[id,JSON.stringify(claims)]); };
    const allowed=async()=> (await db.query('select public.commercial_session_allowed() as allowed')).rows[0].allowed;
    await asUser(); assert.equal(await allowed(),true);
    const dataset={version:2,year:2026,config:{year:2026},sources:[],rows:[],registry:{version:1,entities:[]}};
    await db.query('insert into public.commercial_workspaces(owner_id,year,dataset) values ($1,2026,$2)',[A,JSON.stringify(dataset)]);
    assert.equal((await db.query('select * from public.commercial_workspaces')).rows.length,1);
    await asUser(B); assert.equal(await allowed(),true);
    assert.equal((await db.query('select * from public.commercial_workspaces')).rows.length,0);
    await assert.rejects(()=>db.query('insert into public.commercial_workspaces(owner_id,year,dataset) values ($1,2027,$2)',[A,JSON.stringify({...dataset,year:2027})]),/row-level security/);
    await asUser(A,{session_id:B}); assert.equal(await allowed(),false,'a valid session belonging to B cannot authorize A');
    await asUser(A,{session_id:'not-a-uuid'}); assert.equal(await allowed(),false);
    await asUser(A,{session_id:null}); assert.equal(await allowed(),false);
    for(const table of TABLES) assert.equal((await db.query(`select * from public.${table}`)).rows.length,0);
    await asUser();
    await db.exec(`reset role; update auth.users set raw_app_meta_data='{}',raw_user_meta_data='{"commercial_access":true,"commercial_admin":true,"role":"admin"}' where id='${A}';`);
    await asUser(); assert.equal(await allowed(),false,'self-edited metadata never grants access');
    assert.equal((await db.query('select * from public.commercial_workspaces')).rows.length,0);
    await assert.rejects(()=>db.query('insert into public.commercial_workspaces(owner_id,year,dataset) values ($1,2027,$2)',[A,JSON.stringify({...dataset,year:2027})]),/row-level security/);
    await db.exec(`reset role; update auth.users set raw_app_meta_data='{"commercial_admin":true}',email_confirmed_at=null where id='${A}';`);
    await asUser(); assert.equal(await allowed(),false,'even an admin requires a verified email');
    await db.exec(`reset role; update auth.users set email_confirmed_at=now(),is_anonymous=true where id='${A}';`);
    await asUser(); assert.equal(await allowed(),false);
    await db.exec(`reset role; update auth.users set is_anonymous=false,banned_until=now()+interval '1 hour' where id='${A}';`);
    await asUser(); assert.equal(await allowed(),false);
    await db.exec(`reset role; update auth.users set banned_until=null where id='${A}'; update auth.sessions set not_after=now()-interval '1 second' where id='${A}';`);
    await asUser(); assert.equal(await allowed(),false);
    await db.exec(`reset role; update auth.sessions set not_after=null where id='${A}';`);
    await asUser(); assert.equal(await allowed(),true);
    await db.exec(`reset role; delete from auth.sessions where id='${A}';`);
    await asUser(); assert.equal(await allowed(),false,'logout invalidates old access tokens at RLS, not only in the UI');
    assert.equal((await db.query('select * from public.commercial_workspaces')).rows.length,0);
    await db.exec('reset role; set role anon;');
    for(const table of TABLES) await assert.rejects(()=>db.query(`select * from public.${table}`),/permission denied/);
    await assert.rejects(()=>db.query('select public.commercial_session_allowed()'),/permission denied/);
    await db.exec('reset role;');
    const policies=await db.query("select tablename,permissive from pg_policies where policyname='commercial_active_session'");
    assert.deepEqual(policies.rows.map(x=>x.tablename).sort(),TABLES.slice().sort());
    assert.ok(policies.rows.every(x=>x.permissive==='RESTRICTIVE'));
    const definer=await db.query("select n.nspname,p.proconfig from pg_proc p join pg_namespace n on n.oid=p.pronamespace where p.proname='session_allowed'");
    assert.equal(definer.rows[0].nspname,'commercial_security');
    assert.ok(definer.rows[0].proconfig.includes('search_path=""'));
  } finally { await db.close(); }
});
