"use client";

import { useEffect, useRef, useState } from "react";
import { CalendarDays, Check, ChevronLeft, ChevronRight, Info, LoaderCircle, Pencil, Plus, Trash2 } from "lucide-react";
import { APPOINTMENT_KINDS, APPOINTMENT_STATUSES, TIMEZONES, calendarDays, zonedDateTimeISO, zonedDateTimeInput } from "@/lib/relationship.mjs";
import { deleteEntityAppointment, listEntityAppointments, saveEntityAppointment, type AppointmentInput, type EntityAppointment } from "@/lib/relationship-store";
import type { RegistryEntity } from "@/lib/types";
import { useCalendarToday } from "@/lib/use-calendar-today";
import AppointmentForm, { createAppointmentDraft, type AppointmentDraft } from './appointment-form';
import styles from "./entity-profile.module.css";

type Draft = AppointmentDraft;
const message = (reason: unknown) => reason instanceof Error ? reason.message : "Não foi possível atualizar a agenda.";
const dateLabel = (value: string) => new Date(`${value}T12:00:00Z`).toLocaleDateString("pt-BR", { day: "2-digit", month: "long", timeZone: "UTC" });
const shiftMonth = (month: string, by: number) => { const date = new Date(`${month}-01T12:00:00Z`); date.setUTCMonth(date.getUTCMonth() + by); return date.toISOString().slice(0, 7); };

export default function EntityAgenda({ entity, year, userId, disabled = false, initialDate, onDirtyChange, onAppointmentsChange, onSavingChange }: { entity: RegistryEntity; year: number; userId: string; disabled?: boolean; initialDate?: string; onDirtyChange?: (dirty: boolean) => void; onAppointmentsChange?: () => void; onSavingChange?: (saving: boolean) => void }) {
  const today = useCalendarToday();
  const headingRef = useRef<HTMLHeadingElement>(null);
  const focusDate = initialDate?.startsWith(`${year}-`) ? initialDate : "";
  const [month, setMonth] = useState(focusDate ? focusDate.slice(0, 7) : today.startsWith(`${year}-`) ? today.slice(0, 7) : `${year}-01`);
  const [date, setDate] = useState(focusDate); const [status, setStatus] = useState("all");
  const [appointments, setAppointments] = useState<EntityAppointment[]>([]); const [draft, setDraft] = useState<Draft | null>(null);
  const [editingId, setEditingId] = useState<string>(); const [deletingId, setDeletingId] = useState<string>();
  const [loading, setLoading] = useState(true); const [loadFailed, setLoadFailed] = useState(false); const [saving, setSaving] = useState(false);
  const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const locked = disabled || saving || loading;
  useEffect(() => { let active = true; listEntityAppointments(year, entity.id, userId).then((rows) => { if (active) setAppointments(rows); }).catch((reason) => { if (active) { setError(message(reason)); setLoadFailed(true); } }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [entity.id, year, userId]);
  useEffect(() => { onDirtyChange?.(draft !== null); }, [draft, onDirtyChange]);
  useEffect(() => { if (focusDate) headingRef.current?.focus(); }, [focusDate]);
  useEffect(() => { onSavingChange?.(saving); return () => onSavingChange?.(false); }, [saving, onSavingChange]);
  const dayFor = (item: EntityAppointment) => zonedDateTimeInput(item.startsAt, item.timezone).slice(0, 10);
  const visible = appointments.filter((item) => (date ? dayFor(item) === date : dayFor(item).startsWith(month)) && (status === "all" || item.status === status));
  const counts = new Map<string, number>(); appointments.filter((item) => item.status !== "cancelled").forEach((item) => counts.set(dayFor(item), (counts.get(dayFor(item)) ?? 0) + 1));
  const timezoneLabel = (item: AppointmentInput) => TIMEZONES[item.timezone] ?? item.timezone;
  function startCreate() { const day = date || (today.startsWith(month) ? today : `${month}-01`); setEditingId(undefined); setDeletingId(undefined); setError(""); setNotice(""); setDraft(createAppointmentDraft(day)); }
  function startEdit(item: EntityAppointment) { setEditingId(item.id); setDeletingId(undefined); setError(""); setNotice(""); setDraft({ ...item, startLocal: zonedDateTimeInput(item.startsAt, item.timezone), endLocal: zonedDateTimeInput(item.endsAt, item.timezone) }); }
  function accept(saved: EntityAppointment) { setAppointments((current) => [...current.filter((item) => item.id !== saved.id), saved].sort((a, b) => a.startsAt.localeCompare(b.startsAt))); }
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!draft) return; setSaving(true); setError(""); setNotice(""); try { const saved = await saveEntityAppointment(year, entity, { ...draft, startsAt: zonedDateTimeISO(draft.startLocal, draft.timezone), endsAt: zonedDateTimeISO(draft.endLocal, draft.timezone) }, userId, editingId); accept(saved); const day = dayFor(saved); setMonth(day.slice(0, 7)); setDate(day); setStatus("all"); setDraft(null); setEditingId(undefined); setNotice("Compromisso salvo na agenda."); onAppointmentsChange?.(); } catch (reason) { setError(message(reason)); } finally { setSaving(false); } }
  async function updateStatus(item: EntityAppointment, next: AppointmentInput["status"]) { setSaving(true); setError(""); setNotice(""); try { accept(await saveEntityAppointment(year, entity, { ...item, status: next }, userId, item.id)); setNotice(`Compromisso ${next === "completed" ? "concluído" : next === "cancelled" ? "cancelado" : "reaberto"}.`); onAppointmentsChange?.(); } catch (reason) { setError(message(reason)); } finally { setSaving(false); } }
  async function remove(id: string) { setSaving(true); setError(""); setNotice(""); try { await deleteEntityAppointment(year, entity.id, id, userId); setAppointments((current) => current.filter((item) => item.id !== id)); setDeletingId(undefined); setNotice("Compromisso excluído."); onAppointmentsChange?.(); } catch (reason) { setError(message(reason)); } finally { setSaving(false); } }
  return <section className={styles.section} aria-label={`Agenda de ${entity.name}`}>
    <div className={styles.heading}><div><h3 ref={headingRef} tabIndex={-1}>Agenda de relacionamento</h3><p>Visitas, treinamentos, reuniões e ligações desta unidade.</p></div>{!draft && <button type="button" className="button primary" disabled={locked || loadFailed} onClick={startCreate}><Plus size={17} /> Novo compromisso</button>}</div>
    {error && <div className="message error" role="alert"><Info size={17} />{error}</div>}{notice && <div className="message success" role="status"><Check size={17} />{notice}</div>}
    {loading ? <p className={styles.muted}><LoaderCircle size={17} className="spin" /> Carregando agenda…</p> : draft ? <AppointmentForm year={year} draft={draft} onChange={setDraft} onSubmit={submit} onCancel={() => { setDraft(null); setEditingId(undefined); }} disabled={locked} saving={saving} title={editingId ? 'Editar compromisso' : 'Novo compromisso'} /> : !loadFailed && <>
      <div className={styles.calendar}><div className={styles.calendarHead}><button type="button" className="button quiet" aria-label="Mês anterior" disabled={month === `${year}-01`} onClick={() => { setMonth(shiftMonth(month, -1)); setDate(""); }}><ChevronLeft size={18} /></button><strong>{new Date(`${month}-01T12:00:00Z`).toLocaleDateString("pt-BR", { month: "long", year: "numeric", timeZone: "UTC" })}</strong><button type="button" className="button quiet" aria-label="Próximo mês" disabled={month === `${year}-12`} onClick={() => { setMonth(shiftMonth(month, 1)); setDate(""); }}><ChevronRight size={18} /></button></div><div className={styles.calendarGrid} aria-label="Calendário de compromissos">
        {["Seg", "Ter", "Qua", "Qui", "Sex", "Sáb", "Dom"].map((label) => <span key={label} className={styles.weekday}>{label}</span>)}
        {calendarDays(month).map((day) => <button type="button" key={day.date} className={styles.day} disabled={!day.date.startsWith(`${year}-`)} data-outside={!day.inMonth} data-today={day.date === today} aria-label={`${dateLabel(day.date)}: ${counts.get(day.date) ?? 0} compromissos`} aria-pressed={date === day.date} onClick={() => { setDate(day.date); if (!day.inMonth) setMonth(day.date.slice(0, 7)); }}><span>{day.day}</span>{!!counts.get(day.date) && <span className={styles.dot}>{counts.get(day.date)}</span>}</button>)}
      </div></div>
      <div className={styles.heading}><div><h3>{date ? dateLabel(date) : "Compromissos do mês"}</h3><p>{visible.length} {visible.length === 1 ? "compromisso" : "compromissos"}</p></div><div className={styles.actions}>{date && <button type="button" className="button quiet" onClick={() => setDate("")}>Ver mês inteiro</button>}<label>Situação <select aria-label="Filtrar compromissos por situação" value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">Todas</option>{Object.entries(APPOINTMENT_STATUSES).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div></div>
      <div className={styles.appointments}>{visible.map((item) => <article key={item.id} className={styles.appointment}><div className={styles.heading}><div><span className="section-label">{APPOINTMENT_KINDS[item.kind]}</span><strong style={{ display: "block" }}>{item.title}</strong></div><span className={styles.status} data-status={item.status}>{APPOINTMENT_STATUSES[item.status]}</span></div><time dateTime={item.startsAt}>{new Date(item.startsAt).toLocaleString("pt-BR", { timeZone: item.timezone, day: "2-digit", month: "2-digit", hour: "2-digit", minute: "2-digit" })} – {new Date(item.endsAt).toLocaleString("pt-BR", { timeZone: item.timezone, day: "2-digit", month: "2-digit", hour: "2-digit", minute: "2-digit" })}</time><span className={styles.muted}>{timezoneLabel(item)}</span>{item.location && <p>{item.location}</p>}{item.notes && <p>{item.notes}</p>}<div className={styles.actions}><button type="button" className="button quiet" disabled={locked} onClick={() => startEdit(item)}><Pencil size={15} /> Editar</button>{item.status === "scheduled" ? <><button type="button" className="button secondary" disabled={locked} onClick={() => void updateStatus(item, "completed")}><Check size={15} /> Concluir</button><button type="button" className="button quiet" disabled={locked} onClick={() => void updateStatus(item, "cancelled")}>Cancelar compromisso</button></> : <button type="button" className="button quiet" disabled={locked} onClick={() => void updateStatus(item, "scheduled")}>Reabrir</button>}<button type="button" className="button quiet registry-danger" disabled={locked} onClick={() => setDeletingId(item.id)}><Trash2 size={15} /> Excluir</button></div>{deletingId === item.id && <div className={styles.confirmation} role="alertdialog" aria-label="Excluir compromisso"><p>Excluir “{item.title}” da agenda?</p><div className={styles.actions}><button type="button" className="button secondary" disabled={locked} onClick={() => setDeletingId(undefined)}>Manter compromisso</button><button type="button" className="button registry-danger" disabled={locked} onClick={() => void remove(item.id)}>Confirmar exclusão</button></div></div>}</article>)}</div>
      {!visible.length && <div className="empty compact"><CalendarDays size={28} /><h3>Nenhum compromisso {date ? "neste dia" : "neste mês"}</h3><p>Use “Novo compromisso” para organizar o próximo contato.</p></div>}
    </>}
  </section>;
}
